### ISSUE TITLE
Move to an organization

### ISSUE THREAD

**Issue by jakerr** [chip8-rust/chip8-ui#10]
This will make it easier for us to collaborate and manage the repo / travis CI settings.
I've created a new organization chip8-rust and invited contributor @robo9k. Once the invitation is accepted I'll transfer the repo there (waiting for acceptance so that assigned issues transfer too).

cc: #8 #5

**Comment by robo9k** [comment]
I've just now accepted the invitation to @chip8-rust

**Comment by jakerr** [comment]
Starting this now. After you'll want to update your remote urls:

```
git remote set-url origin https://github.com/chip8-rust/chip8-rust.git
```

**Comment by robo9k** [comment]
Thanks for the heads-up!

I'm not entirely certain, but I might need `Owner` rights to create a token to use `Travis CI` to push to `GitHub Pages`. Investigating..

Edit: It seems like my personal token to push to the chip8-rust/chip8-rust repository should be enough, but I'd rather have a separate token. Investigating..
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by jakerr** [comment]
Not sure if this helps:
https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/

**Comment by robo9k** [comment]
I think pushing commits via Travis could work with encrypted deploy keys. I'll look into that once everything else it set up, but I'm sure there is a way :book:

**Comment by jakerr** [comment]
Sounds good. Let's continue that discussion on the respective issues.
