### ISSUE TITLE
Ambigious naming of `Op` struct

### ISSUE THREAD

**Issue by robo9k** [chip8-rust/chip8-ui#17]
While trying to add `rustdoc` to the `chip8_vm` crate I was slightly irritated by `struct Op`.
Initially I assumed that `Op` would refer to `Opcode`, however upon further inspection it is actually used to store raw instructions.

The difference in assembly being that an `instruction` consists of an `opcode` and zero or more `operands`.
Taking the CHIP-8 "draw" instruction with the `Dxyn` pattern, it consists of the opcode `D`, the `Vx`, `Vy` and `nibble` operands while `DRW` is the mnemonic of the instruction.

Maybe the code should be changed from

``` rust
pub struct Op {
    raw: u16
}
```

to

``` rust
pub struct RawInstruction {
    bits: u16,
}
```

while keeping the name of `enum Instruction`, just changing `::from_op()` to `::from_bits()` or similar.

@jakerr what are your thoughts on this?

**Comment by jakerr** [comment]
Yes, totally agree. Thanks for bringing it up.

I'm not a big fan of `::from_bits(...)` because to me, that name suggests a integral type parameter containing bits like `u8` or something. Maybe `::from_raw(raw: &RawInstruction) -> Instruction`

edit: I see your PR already uses the name I suggested. Cool.

**Comment by robo9k** [comment]
I've found another issue with the `Op` code:

While `Instruction::from_op()` takes care to use e.g. `Op::x()`, one can still create e.g. `AddToI(0xFF)` directly, i.e. an instruction with invalid register.
This might require moving from `tuple structs` to regular `struct`s for (some of) the `Instruction`s, in order to be able to do validation of the arguments in e.g. `::new()`.

I will create a new pull request lateron today.

P.S.: This initial comment was seriously crippled due to using GitHub's mobile version.
