### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by robo9k** [chip8-rust/chip8-ui#7]
Except for `git clone && cargo run` the user might also have to install system packages for OpenGL headers and such.

Using `Gentoo Linux` myself there's been nothing to install on my Desktop, as I get the development headers and libraries for free on this source distro.
Other users however, especially those of OS X or Windows, might have more problems. I assume the `Piston` documentation might have a section for them, so we could just link to that.

**Comment by robo9k** [comment]
Mhm, this should have been closed by ab037c1bf0ffdeeb177f0d7f5484d93b1cdfbda0, but apparently I should have used `fixes #6, fixes #7` in the commit message.

**Comment by jakerr** [comment]
I'm still learning github's magic. I think I should have put the Fixes in my original commit messages rather than in my pull request.

**Comment by robo9k** [comment]
Yes, I think message in the pull request is purely informational and does not show up in the Git commits at all.
I forgot to link to this in my previous comment; https://help.github.com/articles/closing-issues-via-commit-messages/#closing-multiple-issues
