### ISSUE TITLE
Add repository description

### ISSUE THREAD

**Issue by robo9k** [chip8-rust/chip8-ui#9]
GitHub allows to add a repository `Description` and optional `Website`.

![screenshot - 06 02 2015 - 20 35 54](https://cloud.githubusercontent.com/assets/1538025/6086172/fb773a92-ae3f-11e4-82f8-9540cb8466e3.png)

At least the description should be set so users know what they are looking at and possibly improve search results.
I can only edit them for my fork, so @jakerr will need to do this.

**Comment by jakerr** [comment]
Went with

```
Chip-8 virtual machine library and UI built with the Rust programing language
```

for now. Feel free to recommend something better :)
